openapi: "3.0.0"
info:
  version: 1.0.0
  title: "Oraculo API"
servers:
  - url: http://{URL}:3000/
tags:
  - name: Authentication
paths:
  /login:
    post:
      tags:
        - Authentication
      description: Route used to user authentication
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/loginRequest"
      responses:
        "200":
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/loginResponse"
        "400":
          description: Invalid password or registration
        "401":
          description: Forbidden Request
        "500":
          description: Server Error
  /recover:
    post:
      tags:
        - Authentication
      description: Route used to request user recover password
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/recoverRequest"
      responses:
        "204":
          description: Recover request succeeds, access link send to user email
        "400":
          description: User registration not defined
        "401":
          description: Unauthorized request
        "500":
          description: Server Error
  /recover/{link}:
    get:
      tags:
          - Authentication
      parameters:
        - in: path
          name: link
          schema:
            type: string
          required: true
          description: Recovery link to access recover password page
      
      description: Route used to user access recover password page
      responses:
        "204":
          description: Link verificaiton succeeds
        "400":
          description: Invalid link
        "500":
          description: Server Error
    post:
      tags:
        - Authentication
      parameters:
        - in: path
          name: link
          schema:
            type: string
          required: true
          description: Recovery link to access recover password page
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/recoverUpdatePasswordRequest"
      description: Route used to request user recover password
      responses:
        "204":
          description: Recover request succeeds, access link send to user email
        "400":
          description: Invalid password or password confirmation
        "401":
          description: link expired or does not exist
        "500":
          description: Server Error
  /users/create:
    post:
      tags:
        - Admin Functions
      description: Route used by administrator to create new users
      parameters:
        - in: header
          name: x-access-token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/createUserRequest"
      responses:
        "204":
          description: User create with success
        "400":
          description: Invalid parameters or informations already registered
        "403":
          description: User don't have administrator permission to create new user
        "500":
          description: Server Error
  /patrimony/create:
    post:
      tags:
        - Admin Functions
      description: Route used by administrator to create new patrimony registers
      parameters:
        - in: header
          name: x-access-token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/createPatrimonyRequest"
      responses:
        "204":
          description: Patrimony created with success
        "400":
          description: Code already registered or any params missing
        "403":
          description: User don't have administrator permission to create new user
        "500":
          description: Server Error
  
components:
  schemas:
    loginRequest:
      type: object
      properties:
        registration:
          type: string
        password:
          type: string
    loginResponse:
      type: object
      properties:
        token:
          type: string
        userData:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            registration:
              type: string
            permission:
              type: string
    recoverRequest:
      type: object
      properties:
        registration:
          type: string
    recoverUpdatePasswordRequest:
      type: object
      properties:
        password:
          type: string
        password_confirm:
          type: string
    createUserRequest:
      type: object
      properties:
        name:
          type: string
        permission:
          type: number
        email:
          type: string
        registration:
          type: string
    createPatrimonyRequest:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
        state:
          type: string
          enum: ['NOVO', 'BOM', 'INSERVIVEl', 'RECUPERAVEL', 'ANTIECONOMICO']
        entryDate:
          type: string
          format: date 
        lastConferenceDate:
          type: string
          format: date 
        value:
          type: number
          format: double
        patrimonyItens: 
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              localization:
                type: string
              observation:
                type: string
                nullable: true
                

          

    