openapi: "3.0.0"
info:
  version: 1.0.0
  title: ""
servers:
  - url: http://{URL}:3000/
tags:
  - name: Authentication
paths:
  /login:
    post:
      tags:
        - Authentication
      description: Route used to user authentication
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/loginRequest"
      responses:
        "200":
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/loginResponse"
        "400":
          description: Bad Request
        "401":
          description: Forbidden Request
        "500":
          description: Server Error
  
  
components:
  schemas:
    loginRequest:
      type: object
      properties:
        registration:
          type: string
        password:
          type: string
    loginResponse:
      type: object
      properties:
        token:
          type: string
        userData:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            registration:
              type: string
            permission:
              type: string
    