openapi: "3.0.0"
info:
  version: 1.0.0
  title: "PROCAP"
servers:
  - url: http://{URL}:3000/
tags:
  - name: Authentication
  - name: User actions
  - name: Equipments
paths:
  /login:
    post:
      tags:
        - Authentication
      description: Route used to authentication
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/loginRequest"
      responses:
        "200":
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/loginResponse"
        "400":
          description: Bad Request
        "401":
          description: User not authorized
  /recover:
    post:
      tags:
        - Authentication
      description: Route used to recover password
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/recoverPasswordRequest"
      responses:
        "204":
          description: Operation successfully
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                type: object
                properties:
                  error:
                    type: string
  /update-account:
    post:
      tags:
        - User actions
      description: Route used to update operator name and password
      parameters:
        - in: header
          name: x-access-token
          required: true
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/operatorUpdateAccount"
      responses:
        "200":
          description: Operation successfully
          content:
            "application/json":
              schema:
                type: object
                properties:
                  updated:
                    type: boolean
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                type: object
                properties:
                  error:
                    type: string
  /create-account:
    post:
      tags:
        - User actions
      description: Route used to create new users
      parameters:
        - in: header
          name: x-access-token
          required: true
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/createOperatorAccount"
      responses:
        "204":
          description: Operation successfully
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                type: object
                properties:
                  error:
                    type: string
        "403":
          description: User not authorized
  /list-operators:
    get:
      tags:
        - User actions
      description: Route used to list all operators
      parameters:
        - in: header
          name: x-access-token
          required: true
      responses:
        "200":
          description: Operation successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/operators"
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                type: object
                properties:
                  error:
                    type: string
        "403":
          description: User not authorized
  /update-permission:
    post:
      tags:
        - User actions
      description: Route update users permissions and lins
      parameters:
        - in: header
          name: x-access-token
          required: true
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/updateOperatorPermissionAndLine"
      responses:
        "200":
          description: Operation successfully
          content:
            "application/json":
              schema:
                type: boolean
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                type: object
                properties:
                  error:
                    type: string
        "403":
          description: User not authorized
  /delete-operator/{id}:
    delete:
      tags:
        - User actions
      description: Delete operator registered on system
      parameters:
        - in: header
          name: x-access-token
          required: true
      responses:
        "200":
          description: Operation successfully
          content:
            "application/json":
              schema:
                type: boolean
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                type: object
                properties:
                  error:
                    type: string
        "403":
          description: User not authorized
  /equipments:
    get:
      tags:
        - Equipments
      description: list all equipments
      parameters:
        - in: header
          name: x-access-token
          required: true
      responses:
        "200":
          description: Operation successfully
          content:
            "application/json":
             schema:
              $ref: "#/components/schemas/equipments"
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                type: object
                properties:
                  error:
                    type: string
        "403":
          description: User not authorized
  /equipments/{line}:
    get:
      tags:
        - Equipments
      description: list all equipments
      parameters:
        - in: header
          name: x-access-token
          required: true
      responses:
        "200":
          description: Operation successfully
          content:
            "application/json":
             schema:
              $ref: "#/components/schemas/equipments"
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                type: object
                properties:
                  error:
                    type: string
        "403":
          description: User not authorized
components:
  schemas:
    loginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    loginResponse:
      type: object
      properties:
        accessToken:
          type: string
        operatorAccount:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            line:
              type: array
            permission:
              type: string
    recoverPasswordRequest:
      type: object
      properties:
        email:
          type: string
    operatorUpdateAccount:
      type: object
      properties:
        name:
          type: string
        password:
          type: string
        passwordConfirmation:
          type: string
    createOperatorAccount:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        permission:
          type: string
        line:
          type: array
          items:
            type: string
    updateOperatorPermissionAndLine:
      type: object
      properties:
        userId:
          type: string
        permission:
          type: string
        line:
          type: array
          items:
            type: string
    operators:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
          line:
            type: string
          tag:
            type: string
          type:
            type: string
    equipments:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
          email:
            type: string
          permission:
            type: string
          line:
            type: array
            items:
              type: string
